name: Tag a dev release on GitHub using the current version according to Cargo.toml
on:
  push:
    branches: [ main ]
jobs:
  make-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag-name }}
    steps:
      - name: Checkout Spindrift
        uses: actions/checkout@v3

      - name: generate tag
        id: generate-tag
        run: |
          echo "## Creating Tag" >> $GITHUB_STEP_SUMMARY
          echo "CANDIDATE_TAG=$(grep '^version' Cargo.toml | awk '{print $3}' | sed -r 's/\"//g')-dev+$(date +%y%m%d)" >> $GITHUB_ENV
          echo "**`$CANDIDATE_TAG`**: ${{ env.CANDIDATE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "NEEDED_PART=$(git show-ref --tags -d | grep ${{ env.CANDIDATE_TAG }} | wc -l)" >> $GITHUB_ENV
          echo "**`$NEEDED_PART`**: ${{ env.NEEDED_PART }}" >> $GITHUB_STEP_SUMMARY
          if [ ${{ env.NEEDED_PART }} -eq 0 ] ; then
            echo "::set-output name=tag-name::${{ env.CANDIDATE_TAG }}"
            echo "Using tag name `${{ env.CANDIDATE_TAG }}`" >> $GITHUB_STEP_SUMMARY
          else
            echo "::set-output name=tag-name::${{ env.CANDIDATE_TAG }}.${{ env.NEEDED_PART }}"
            echo "Using tag name `${{ env.CANDIDATE_TAG }}.${{ env.NEEDED_PART }}`" >> $GITHUB_STEP_SUMMARY
          fi
        
      - name: tag a release
        run: |
          git tag ${{ steps.generate-tag.outputs.tag-name }}
          git push origin tag ${{ steps.generate-tag.outputs.tag-name }}

